In [1]:
import numpy as np
import sys

In [2]:
arr = np.array([10, 20])
arr

array([10, 20])

In [3]:
arr.size

2

In [4]:
arr.item

<function ndarray.item>

In [5]:
arr.itemsize

4

In [6]:
arr.shape

(2,)

In [7]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [9]:
arr.ndim

1

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.nbytes

8

In [14]:
arr = np.array([10.5, 54.4, 86.1])
arr

array([10.5, 54.4, 86.1])

In [15]:
arr.size

3

In [16]:
arr.shape

(3,)

In [19]:
print(arr.__sizeof__)

<built-in method __sizeof__ of numpy.ndarray object at 0x0000027845D37E10>


In [20]:
arr.dtype

dtype('float64')

In [21]:
arr.itemsize

8

In [22]:
arr.nbytes

24

In [30]:
arr = np.array(['adcb', 'b'])
arr.itemsize

16

In [31]:
arr.nbytes

32

In [25]:
arr.shape

(2,)

In [26]:
arr.itemsize

4

In [32]:
arr.dtype

dtype('<U4')

In [33]:
arr.size

2

In [35]:
arr = np.array([[10, 20], [30, 40]])
arr

array([[10, 20],
       [30, 40]])

In [36]:
arr.size

4

In [37]:
arr.shape

(2, 2)

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr.itemsize

4

In [40]:
arr.ndim

2

In [41]:
arr.nbytes

16

In [42]:
arr = np.arange(5, 50, 9)
arr

array([ 5, 14, 23, 32, 41])

In [45]:
np.ones([7, 8], dtype=np.int32)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [47]:
np.zeros([4, 3, 2], np.int8)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int8)

In [51]:
np.random.random(3)

array([0.53860226, 0.90491328, 0.97232022])

In [80]:
np.random.randint(1, 100, [7, 8])

array([[88, 16, 30, 40, 87, 85, 14, 67],
       [56, 70, 40,  6,  8, 36, 45, 79],
       [23, 46, 53, 80,  9, 23, 26, 64],
       [74,  3, 39, 88, 74, 29, 62, 55],
       [60, 20, 60, 28, 45, 22, 61, 76],
       [75, 77, 94, 98, 65, 45, 80, 34],
       [86,  2, 57, 40, 16, 81, 23, 64]])