In [2]:
import numpy as np

In [7]:
arr = np.arange(0, 15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr = arr.reshape([5, 3])
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
arr = np.random.randint(1, 50, [2, 3])
arr

array([[ 1, 33, 37],
       [19, 26, 23]])

In [21]:
ar = arr + 5
ar

array([[ 6, 38, 42],
       [24, 31, 28]])

In [22]:
arr * ar

array([[   6, 1254, 1554],
       [ 456,  806,  644]])

In [23]:
a = np.arange(1, 11) * 2
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
a[-5]

12

In [25]:
a[-1]

20

In [28]:
a[[5, 8]]

array([12, 18])

In [29]:
a[a>10]

array([12, 14, 16, 18, 20])

In [30]:
a[2:8:2]

array([ 6, 10, 14])

In [31]:
import pandas as pd

In [32]:
s = pd.Series([10, 45])
s

0    10
1    45
dtype: int64

In [33]:
s.dtype

dtype('int64')

In [34]:
s.size

2

In [35]:
s.shape

(2,)

In [36]:
s.nbytes

16

In [37]:
s.ndim

1

In [38]:
s.index

RangeIndex(start=0, stop=2, step=1)

In [39]:
s.values

array([10, 45], dtype=int64)